### ISSUE TITLE
Error while doing test transaction 

### ISSUE THREAD

**Issue by ajayglobalnest** [citruspay/citruspay-ios-sdk#15]
Hello There , 

I am integrating Citrus Payment gateway to our iOS application . I am trying to use PlugNPlay framework for payments but i am facing an issue while doing a test transaction receiving below error . 

"value":null,"currency":"INR" . - Value going null
2017-02-06 16:27:19.760 [Verbose] > [CitrusPay SDK] Version 4.1.2 : billJson {"merchantTxnId":"xxxxxxxxxxxxxxx","amount":{"value":null,"currency":"INR"},"requestSignature":"xxxxxxxxxxxxxxx","merchantAccessKey":"xxxxxxxxxxxxxx","returnUrl":"https:\/\/eventdex.com\/citrus-mobile\/requestData.php?secret_key=xxxxxxxxxxxxxx?amount=1.00"}

2017-02-06 16:27:19.760 [Verbose] > [CitrusPay SDK] Version 4.1.2 : signature (null) 

2017-02-06 16:27:19.760 CitrusTestApp[5510:214817] error Invalid JSON data: Value of required model key value is null

**Comment by mukesh122** [comment]
@ajayglobalnest  looks issues with your bill generator json response format which is amount value is null, check our bill generator format.
or try out with our sample bill url so you will get know root cause & fix out issues.

**Comment by ajayglobalnest** [comment]
Hi Mukesh , is it the one which we configured on server you are talking about .  I dont generate billurl i am using plugnplay framework  , so as far i knew it will be generated by Server . 

or your sdk method .

**Comment by mukesh122** [comment]
For further more support contact to concern team - developer.support@citruspay.com

**Comment by maheshlantech** [comment]
which page get payment json Response in ios.

**Comment by maheshlantech** [comment]
[CitrusPay SDK] Version 4.1.8 : Property error Value: Error Domain=com.citrus.errorDomain Code=7007 "Server threw an error
code 401" UserInfo={NSLocalizedDescription=Server threw an error
code 401}

**Comment by srikanthiphoneapps** [comment]
I am using citrus direct payment options. Net banking is showing error. Please help me on this. Below is the log data.


[CitrusPay SDK] Version 4.1.8 : Property headers Value: {
    Cookie = "";
}
Citrus[2107:1551457] [CitrusPay SDK] Version 4.1.8 : restRequest JSON> (null)

Citrus[2107:1551538] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

Citrus[2107:1553154] [CitrusPay SDK] Version 4.1.8 : signature (null)
 
Error : Malformed JSON. Check the JSONModel data input.

Citrus[2117:1561989] [BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
