### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$__TtC14CitrusGraphics14CitrusGraphics

### ISSUE THREAD

**Issue by krishnans** [citruspay/citruspay-ios-sdk#28]
While using the latest version i am getting the following error
dyld: Symbol not found: _OBJC_CLASS_$__TtC14CitrusGraphics14CitrusGraphics.

**Comment by vipin04** [comment]
Please make sure to use the .framework files from releases page:
https://github.com/citruspay/citruspay-ios-sdk/releases
Avoid using pre-released products as it may not be stable for production. 

Your error seems to be occurring because of using CitrusGraphics 2.0 with older Citrus frameworks.
Please use a compatible version of citrus graphics 1.1.3

**Comment by krishnans** [comment]
I am using 4.1.7 version of citrus pay.  I did an pod update and got this error after that. 
CitrusPay podspec has a CitrusGraphics dependency and CitrusGraphics podspec points to 2.0 version.

**Comment by vipin04** [comment]
Please hardcoded compatible CitrusGraphics version in your podspec

pod 'CitrusGraphics', '~> 1.1.3'

Make sure this version gets picked up while running pod install. Clean the pod cache.

**Comment by krishnans** [comment]
Its working now.  Thanks as lot.
